# Cursor Size
env = XCURSOR_SIZE,24

# Qt Environment
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
#env = QT_STYLE_OVERRIDE,qt6ct

env = GDK_BACKEND=wayland,x11

# XDG Environment
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# GTK Theme
env = GTK_THEME,Tokyonight-Dark
env = GTK2_RC_FILES,/usr/share/themes/Tokyonight-Dark/gtk-2.0/gtkrc

# Screenshots Folder
env = HYPRSHOT_DIR,/home/jkholick/Pictures/Screenshots/

# Nvidia Environments
#env = LIBVA_DRIVER_NAME,nvidia
#env = __GLX_VENDOR_LIBRARY_NAME,nvidia
#env = __GL_VRR_ALLOWED,1
#env = WLR_NO_HARDWARE_CURSORS,1

# Intel iGPU 
#env = __GLX_VENDOR_LIBRARY_NAME,mesa
#env = LIBVA_DRIVER_NAME,i965

#env = WLR_DRM_DEVICES,/dev/dri/by-path/pci-0000:00:02.0-card
#env = AQ_DRM_DEVICES,/dev/dri/by-path/pci-0000:00:02.0-card
#env = __EGL_VENDOR_LIBRARY_FILENAMES,/usr/share/glvnd/egl_vendor.d/50_mesa.json
#env = AQ_DRM_NO_MODIFIERS,1
#env = AQ_DRM_NO_EXPLICIT_SYNC,1

# Fix dolphin xdg mime menu
#env = XDG_MENU_PREFIX,plasma- kbuildsycoca6
#
# Note to self you can just make the thing work by
# install archlinux-xdg-menu pakage 
# Run sudo update-desktop-database
# copy sudo mv /etc/xdg/menus/arch-applications.menu /etc/xdg/menus/applications.menu

#Editor
env = EDITOR,/bin/nvim
