# Picture in Picture
windowrule {
  name = PiP
  match:title = ^(Picture(-| )in(-| )[Pp]icture)$
  float = on
  keep_aspect_ratio = on
  pin = on
  size = (monitor_w*0.25) (monitor_h*0.25)
  move = (monitor_w*0.74) (monitor_h*0.73)
}

# Discord popout
windowrule {
  name = Discord_Popout
  match:title = ^(Discord Popout)$
  float = on
  keep_aspect_ratio = on
  pin = on
  size = (monitor_w*0.25) (monitor_h*0.25)
  move = (monitor_w*0.74) (monitor_h*0.73)
}

# Clipboard Float
windowrule {
  name = Clipse_clipboard
  match:title = (clipse) 
  float = on
  size = (monitor_w*0.50) (monitor_h*0.70) 
}

# KDE Pointer
windowrule {
  name = KDE_Pointer
  match:title = ^(KDE Connect Daemon)$
  float = on
  pin = on
  no_blur = on
  size = monitor_w monitor_h
}

# Steam
#windowrule = stayfocused, match:title:^()$,class:^(steam)$
##windowrule = minsize 1 1, match:title:^()$,class:^(steam)$
#windowrule = float, match:title:^(Friends List)$
#windowrule = size 44% 82%, match:title:^(Friends List)$

# Lutris stop floating
#windowrule = tile, class:^(lutris)$

# Games
windowrule = immediate on, match:class ^(Minecraft)
windowrule = immediate on, match:class ^(nfs13.exe)
windowrule = fullscreen on, match:class ^(tod.exe)

#MC laucher thingy
windowrule {
  name = MC_launcher
  float = on
  match:title = (Select Your Minecraft Launcher Location)
  size = (window_w*1.5) (window_h*1.5)
  center = on
}
